apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  namespace: crossplane-system
  name: krateo-provider-github
spec:
  package: 'ghcr.io/krateoplatformops/provider-github:VERSION'
  packagePullPolicy: IfNotPresent
